CREATE TABLE IF NOT EXISTS DMF_CONFIG (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    DATABASE_NAME VARCHAR(255) NOT NULL,
    SCHEMA_NAME VARCHAR(255) NOT NULL,
    TABLE_NAME VARCHAR(255) NOT NULL,
    COLUMN_NAMES VARCHAR(4000),
    DMF_NAME VARCHAR(500) NOT NULL,
    DMF_SCHEDULE VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    NOTES VARCHAR(2000)
);

COMMENT ON TABLE DMF_CONFIG IS 'Configuration table for managing Data Metric Functions (DMFs) across tables';
COMMENT ON COLUMN DMF_CONFIG.DATABASE_NAME IS 'Target database name';
COMMENT ON COLUMN DMF_CONFIG.SCHEMA_NAME IS 'Target schema name';
COMMENT ON COLUMN DMF_CONFIG.TABLE_NAME IS 'Target table name';
COMMENT ON COLUMN DMF_CONFIG.COLUMN_NAMES IS 'Comma-separated column names for column-level DMFs. NULL for table-level DMFs like ROW_COUNT';
COMMENT ON COLUMN DMF_CONFIG.DMF_NAME IS 'Fully qualified DMF name (e.g., SNOWFLAKE.CORE.NULL_COUNT or custom.schema.my_dmf)';
COMMENT ON COLUMN DMF_CONFIG.DMF_SCHEDULE IS 'Schedule: N MINUTE, USING CRON expression, or TRIGGER_ON_CHANGES';
COMMENT ON COLUMN DMF_CONFIG.IS_ACTIVE IS 'Enable/disable DMF without deleting config entry';
COMMENT ON COLUMN DMF_CONFIG.NOTES IS 'Documentation or purpose of this DMF assignment';
