INSERT INTO DMF_CONFIG (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAMES, DMF_NAME, DMF_SCHEDULE, NOTES)
VALUES
('DQ_ANALYST_DB', 'DQ_RESULTS', 'CUSTOMERS', 'EMAIL', 'SNOWFLAKE.CORE.NULL_COUNT', '5 MINUTE', 'Monitor null email addresses'),
('DQ_ANALYST_DB', 'DQ_RESULTS', 'CUSTOMERS', 'PHONE', 'SNOWFLAKE.CORE.NULL_COUNT', '5 MINUTE', 'Monitor null phone numbers'),
('DQ_ANALYST_DB', 'DQ_RESULTS', 'CUSTOMERS', NULL, 'SNOWFLAKE.CORE.ROW_COUNT', 'TRIGGER_ON_CHANGES', 'Track total customer count'),
('DQ_ANALYST_DB', 'DQ_RESULTS', 'CUSTOMERS', 'ACCOUNT_NUMBER', 'SNOWFLAKE.CORE.DUPLICATE_COUNT', 'USING CRON 0 6 * * * UTC', 'Check for duplicate customer IDs'),
('DQ_ANALYST_DB', 'DQ_RESULTS', 'CUSTOMERS', 'ACCOUNT_NUMBER', 'SNOWFLAKE.CORE.UNIQUE_COUNT', 'USING CRON 0 8 * * * UTC', 'Track unique order count'),
('DQ_ANALYST_DB', 'DQ_RESULTS', 'CUSTOMERS', NULL, 'SNOWFLAKE.CORE.FRESHNESS', 'TRIGGER_ON_CHANGES', 'Monitor data freshness');

--SELECT * FROM DMF_CONFIG;